name: TestPR
on: workflow_dispatch
jobs:
  CheckLastPR:
    runs-on: ubuntu-latest
    name: CheckLastPR
    steps:
      - run: |
          echo "Hello"
          gh pr list --search "6e19442492c12b2ba0a9d12e2882b77592512e43" --state merged
    
