name: TestPR
on: workflow_dispatch
jobs:
  CheckLastPR:
    runs-on: ubuntu-latest
    name: CheckLastPR
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: |
          ls -la
          SHAA=$(cat .git/refs/heads/main)
          echo "SHA= $SHAA"
          gh pr list --search "$SHAA" --state merged
        env:
          GH_TOKEN: ${{ github.token }}
    
